### ISSUE TITLE
 [info] Discovering your project

### ISSUE THREAD

**Issue by ebachard** [songtianyi/motionLib#1]
Hello,

Dues to stupid github (no way to discover easely what exists), I searched since a long while, but I discovered your code only today. I'll try to find some time asap, I'll try to build it on Linux, and test it of course !

My need is simply cubic bezier curve, but the other object you implemented look very interesting.

Thanks a lot for sharing your code (and your knowledge), much appreciated !

-- 
ericb

**Comment by songtianyi** [comment]
Thanks.
